/**
 * Generates the Android launcher icon set from the SAME SVG master as everything else.
 *
 * Two kinds, and the distinction matters:
 *   ic_launcher / ic_launcher_round  legacy, plated - the launcher draws them as-is.
 *   ic_launcher_foreground           adaptive, from the MASKABLE variant - Android composes
 *                                    it over its own background and applies its own mask,
 *                                    so a baked plate here would render as a rounded square
 *                                    floating inside a circle.
 *
 *   node tools/icon-android.mjs
 */
import { readFileSync, mkdirSync, writeFileSync, existsSync } from 'node:fs';
import { join, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { chromium } from 'playwright';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(ROOT, 'src/assets/icon');
const RES = join(ROOT, 'android/app/src/main/res');

if (!existsSync(RES)) {
  console.error('  no android/ project - run `npx cap add android` first');
  process.exit(1);
}

/** Launcher icon is 48dp; foreground is 108dp because the mask crops to the middle 72dp. */
const DENSITIES = [
  ['mdpi', 1],
  ['hdpi', 1.5],
  ['xhdpi', 2],
  ['xxhdpi', 3],
  ['xxxhdpi', 4],
];

const browser = await chromium.launch();

async function raster(svgFile, px, transparent) {
  const svg = readFileSync(join(SRC, svgFile), 'utf8');
  const page = await browser.newPage({ viewport: { width: px, height: px } });
  await page.setContent(
    `<!doctype html><meta charset="utf-8">
     <style>html,body{margin:0;background:transparent}svg{display:block;width:${px}px;height:${px}px}</style>
     ${svg}`,
    { waitUntil: 'load' },
  );
  const buf = await page.screenshot({ omitBackground: transparent });
  await page.close();
  return buf;
}

const written = [];
for (const [density, factor] of DENSITIES) {
  const dir = join(RES, `mipmap-${density}`);
  mkdirSync(dir, { recursive: true });

  const legacy = Math.round(48 * factor);
  const fg = Math.round(108 * factor);

  writeFileSync(join(dir, 'ic_launcher.png'), await raster('icon.svg', legacy, false));
  writeFileSync(join(dir, 'ic_launcher_round.png'), await raster('icon.svg', legacy, false));
  // From icon-foreground.svg, NOT icon-maskable.svg. The maskable variant paints its own
  // full-bleed ground, so omitBackground could never make it transparent - that is why the
  // shipped foreground had alpha 255 in every corner.
  writeFileSync(join(dir, 'ic_launcher_foreground.png'), await raster('icon-foreground.svg', fg, true));
  writeFileSync(join(dir, 'ic_launcher_monochrome.png'), await raster('icon-monochrome.svg', fg, true));
  written.push(`mipmap-${density}  legacy ${legacy}px  foreground ${fg}px`);
}
await browser.close();

// Adaptive icon: Android composes foreground over background and masks the result itself.
const adaptive = `<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by tools/icon-android.mjs. Do not edit. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/spGround"/>
    <foreground android:drawable="@mipmap/ic_launcher_foreground"/>
    <monochrome android:drawable="@mipmap/ic_launcher_monochrome"/>
</adaptive-icon>
`;
for (const name of ['mipmap-anydpi-v26']) {
  const dir = join(RES, name);
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, 'ic_launcher.xml'), adaptive);
  writeFileSync(join(dir, 'ic_launcher_round.xml'), adaptive);
}

console.log('  android launcher icons:');
for (const w of written) console.log(`    ${w}`);
console.log('    mipmap-anydpi-v26  adaptive ic_launcher.xml + ic_launcher_round.xml');
