/**
 * AEGIS HOST - a line that holds while the sky argues above it.
 *
 * Structurally the opposite of the breach host: the cast barely moves and the LIGHT does all
 * the travelling. Three of its figures share the stance `planted`, which is the point - a
 * shield line is a wall of repetition - so every one of them carries a different attribute
 * and the loop alternates a held pulse against a cast bolt.
 *
 * Sources: the bolt, the tasselled storm-shield, the severed mask carried on a pole and the
 * toppled stone titan are read from Hesiod and Homer directly. Bronze, cloth and stone only.
 *
 * IP: original. Archaic-Mediterranean military furniture from primary text, no adaptation,
 * no character, no crest that belongs to anyone.
 */

import { defineTimeline } from '../types';
import { defineRoster, lit, rest, type DesignedRoster } from './design';

export const AEGIS_HOST: DesignedRoster = defineRoster({
  id: 'aegis-host',
  displayName: 'The Aegis Line',
  figures: [
    {
      id: 'ah-colonnade-rank',
      tier: 'horizon',
      silhouette: 'flock',
      widthFrac: 0.09,
      heightFrac: 0.06,
      anchor: { xFrac: -0.7, yFrac: 0 },
      opacity: 0.3,
      design: {
        attribute: 'pike-bundle',
        form: 'detached-mass',
        stance: 'braced',
        note: 'Dominant: pikes standing well above the rank, clear of every head. Stance: the whole rank set and braced.',
      },
    },
    {
      id: 'ah-bolt-caster',
      tier: 'horizon',
      silhouette: 'lancer',
      widthFrac: 0.06,
      heightFrac: 0.16,
      anchor: { xFrac: -0.36, yFrac: 0.02 },
      opacity: 0.34,
      design: {
        attribute: 'forked-bolt',
        form: 'detached-mass',
        stance: 'lunging',
        note: 'Dominant: a forked bolt already loosed, hanging in air ahead of the hand. Stance: full throwing lunge.',
      },
    },
    {
      id: 'ah-chariot-rider',
      tier: 'horizon',
      // Not `rider`: that shape is registered CLOSE_TIERS only, because twelve rings of
      // mount-plus-standing-figure turn to mush at horizon scale. `siege-frame` carries the
      // same wheeled read in eight, and the wheel voids are what the attribute is anyway.
      silhouette: 'siege-frame',
      widthFrac: 0.08,
      heightFrac: 0.12,
      anchor: { xFrac: 0, yFrac: 0 },
      opacity: 0.32,
      design: {
        attribute: 'wheel-rim',
        form: 'evenodd-hole',
        stance: 'pivoting',
        note: 'Dominant: a wheel read by the voids between its spokes. Stance: turning across frame, weight outboard.',
      },
    },
    {
      id: 'ah-mask-standard',
      tier: 'horizon',
      silhouette: 'standard-bearer',
      widthFrac: 0.05,
      heightFrac: 0.17,
      anchor: { xFrac: 0.36, yFrac: 0 },
      opacity: 0.36,
      design: {
        attribute: 'mask-plate',
        form: 'detached-mass',
        stance: 'planted',
        note: 'Dominant: a face-plate carried high on a pole, well clear of its own head. Stance: planted, feet together.',
      },
    },
    {
      id: 'ah-line-archer',
      tier: 'horizon',
      silhouette: 'archer',
      widthFrac: 0.05,
      heightFrac: 0.11,
      anchor: { xFrac: 0.68, yFrac: 0 },
      opacity: 0.3,
      design: {
        attribute: 'quiver-rack',
        form: 'detached-mass',
        stance: 'kneeling',
        note: 'Dominant: a shaft rack stuck upright an arm away. Stance: kneeling behind the line, drawing low.',
      },
    },
    {
      id: 'ah-wall-shieldbearer',
      tier: 'mid',
      silhouette: 'shieldbearer',
      widthFrac: 0.12,
      heightFrac: 0.28,
      anchor: { xFrac: -0.64, yFrac: 0 },
      opacity: 0.54,
      design: {
        attribute: 'tower-shield',
        form: 'evenodd-hole',
        stance: 'planted',
        note: 'Dominant: a shield whose boss is a punched ring of sky. Stance: planted square, shield locked to ground.',
      },
    },
    {
      id: 'ah-bronze-warden',
      tier: 'mid',
      silhouette: 'colossus',
      widthFrac: 0.16,
      heightFrac: 0.38,
      anchor: { xFrac: -0.24, yFrac: 0 },
      opacity: 0.58,
      design: {
        attribute: 'brazier-bowl',
        form: 'detached-mass',
        stance: 'striding',
        note: 'Dominant: a standing bowl of fire it walks past, never touching. Stance: mid-stride, arms counter-swung.',
      },
    },
    {
      id: 'ah-crested-lancer',
      tier: 'mid',
      silhouette: 'lancer',
      widthFrac: 0.11,
      heightFrac: 0.3,
      anchor: { xFrac: 0.18, yFrac: 0 },
      opacity: 0.56,
      design: {
        attribute: 'crest-fin',
        form: 'evenodd-hole',
        stance: 'leaning',
        note: 'Dominant: a transverse crest read by the slot cut between crest and skull. Stance: leaning into the shove.',
      },
    },
    {
      id: 'ah-siege-ram',
      tier: 'mid',
      silhouette: 'siege-frame',
      widthFrac: 0.17,
      heightFrac: 0.26,
      anchor: { xFrac: 0.62, yFrac: 0 },
      opacity: 0.6,
      design: {
        attribute: 'counterweight-boom',
        form: 'detached-mass',
        stance: 'braced',
        note: 'Dominant: a weighted boom swung out beyond the frame. Stance: legs spread and braced against recoil.',
      },
    },
    {
      id: 'ah-gate-colossus',
      tier: 'fore',
      silhouette: 'colossus',
      widthFrac: 0.28,
      heightFrac: 0.7,
      anchor: { xFrac: -0.66, yFrac: 0 },
      opacity: 0.86,
      design: {
        attribute: 'hollow-crown',
        form: 'evenodd-hole',
        stance: 'planted',
        note: 'Dominant: a helm whose eye-slot is a void straight through. Stance: planted dead still, fists closed.',
      },
    },
    {
      id: 'ah-fallen-titan',
      tier: 'fore',
      silhouette: 'stonewalker',
      widthFrac: 0.34,
      heightFrac: 0.48,
      anchor: { xFrac: 0.06, yFrac: 0 },
      opacity: 0.82,
      design: {
        attribute: 'split-jaw',
        form: 'evenodd-hole',
        stance: 'prone',
        note: 'Dominant: a jaw fallen open around a punched hole. Stance: face down across the frame, one arm folded under.',
      },
    },
    {
      id: 'ah-line-standard',
      tier: 'fore',
      silhouette: 'standard-bearer',
      widthFrac: 0.22,
      heightFrac: 0.58,
      anchor: { xFrac: 0.66, yFrac: 0 },
      opacity: 0.8,
      design: {
        attribute: 'banner-cross',
        form: 'evenodd-hole',
        stance: 'leaning',
        note: 'Dominant: a banner that is mostly the holes burnt through it. Stance: leaning back against the pole load.',
      },
    },
  ],
  timeline: defineTimeline('aegis-host', 30000, [
    lit({
      id: 'ah-b1',
      title: 'the line locks',
      atMs: 0,
      durationMs: 2000,
      pressureDelayMs: 720,
      shape: 'pulse',
      attackMs: 600,
      holdMs: 600,
      releaseMs: 800,
      peak: { emisIntensity: 1.5, brazierGlow: 0.9 },
    }),
    lit({
      id: 'ah-b2',
      title: 'bolt cast, far off',
      atMs: 2600,
      durationMs: 900,
      pressureDelayMs: 750,
      shape: 'strike',
      attackMs: 30,
      holdMs: 130,
      releaseMs: 740,
      peak: { emisIntensity: 3.6, skyDim: 0.42, rimBoost: 2 },
    }),
    lit({
      id: 'ah-b3',
      title: 'the shields answer',
      atMs: 4000,
      durationMs: 1600,
      pressureDelayMs: 710,
      shape: 'pulse',
      attackMs: 400,
      holdMs: 500,
      releaseMs: 700,
      peak: { brazierGlow: 1.8, emisIntensity: 1.9 },
    }),
    lit({
      id: 'ah-b4',
      title: 'the colonnade dims',
      atMs: 6200,
      durationMs: 2000,
      pressureDelayMs: 780,
      shape: 'smother',
      attackMs: 600,
      holdMs: 600,
      releaseMs: 800,
      peak: { skyDim: 0.6, emisIntensity: 0.6 },
    }),
    rest({ id: 'ah-b5', title: 'dust between the ranks', atMs: 8800, durationMs: 3000 }),
    lit({
      id: 'ah-b6',
      title: 'bolt cast, overhead',
      atMs: 12200,
      durationMs: 1000,
      pressureDelayMs: 800,
      shape: 'strike',
      attackMs: 25,
      holdMs: 175,
      releaseMs: 800,
      peak: { emisIntensity: 5.5, skyDim: 0.62, rimBoost: 3.2 },
    }),
    lit({
      id: 'ah-b7',
      title: 'the wall bows',
      atMs: 13800,
      durationMs: 2200,
      pressureDelayMs: 700,
      shape: 'swell',
      attackMs: 800,
      holdMs: 600,
      releaseMs: 800,
      peak: { shaftOpacity: 0.5, emisIntensity: 2.2, brazierGlow: 1.5 },
    }),
    lit({
      id: 'ah-b8',
      title: 'the titan goes down',
      atMs: 16600,
      durationMs: 1400,
      pressureDelayMs: 790,
      shape: 'strike',
      attackMs: 40,
      holdMs: 260,
      releaseMs: 1100,
      peak: { emisIntensity: 3, rimBoost: 2.4, brazierGlow: 2.6, skyDim: 0.2 },
    }),
    lit({
      id: 'ah-b9',
      title: 'ash settles over bronze',
      atMs: 18600,
      durationMs: 2400,
      pressureDelayMs: 760,
      shape: 'smother',
      attackMs: 700,
      holdMs: 900,
      releaseMs: 800,
      peak: { skyDim: 0.74, emisIntensity: 0.45, shaftOpacity: 0.1 },
    }),
    lit({
      id: 'ah-b10',
      title: 'the line is still there',
      atMs: 21600,
      durationMs: 3800,
      pressureDelayMs: 740,
      shape: 'swell',
      attackMs: 1500,
      holdMs: 1200,
      releaseMs: 1100,
      peak: { emisIntensity: 1.8, brazierGlow: 1.2, shaftOpacity: 0.28, rimBoost: 0.8 },
    }),
  ]),
});
