/**
 * ASHFALL WAR - a war fought along a shrine approach while ash falls on it.
 *
 * The slowest loop of the seven and the only one with TWO rests, which is the whole design:
 * thirty-six seconds in which almost nothing happens twice, so the paired cuts at nineteen
 * and twenty seconds arrive with no rhythm to hide behind. The loop closes on a smother and
 * then a very long, very low swell - the road after, not the fight.
 *
 * Cast logic: an approach is a corridor, so this roster is built out of THINGS THAT FRAME -
 * a gate yoke, a hanging bell, a stone lantern, a rank of brims - and the two moving figures
 * (the masked runner, the mounted blade) are the only diagonals in it. Stillness is the
 * baseline here and movement is the exception, which is the reverse of the breach host.
 *
 * IP: original. Shrine and warring-states furniture drawn from architecture rather than from
 * any adaptation of it. No crest, no house mark, no borrowed silhouette, no colour identity.
 */

import { defineTimeline } from '../types';
import { defineRoster, lit, rest, type DesignedRoster } from './design';

export const ASHFALL_WAR: DesignedRoster = defineRoster({
  id: 'ashfall-war',
  displayName: 'The Ashfall War',
  figures: [
    {
      id: 'aw-approach-rank',
      tier: 'horizon',
      silhouette: 'flock',
      widthFrac: 0.09,
      heightFrac: 0.07,
      anchor: { xFrac: -0.7, yFrac: 0 },
      opacity: 0.3,
      design: {
        attribute: 'conical-hat',
        form: 'evenodd-hole',
        stance: 'striding',
        note: 'Dominant: a scalloped brim line, each brim cut off its shoulders by a real gap. Stance: a column in step.',
      },
    },
    {
      id: 'aw-bell-shrine',
      tier: 'horizon',
      silhouette: 'siege-frame',
      widthFrac: 0.07,
      heightFrac: 0.16,
      anchor: { xFrac: -0.34, yFrac: 0.04 },
      opacity: 0.32,
      design: {
        attribute: 'bell-tree',
        form: 'detached-mass',
        stance: 'suspended',
        note: 'Dominant: one heavy bell hanging in the frame with air all round it. Stance: the frame hung off its posts.',
      },
    },
    {
      id: 'aw-ash-archer',
      tier: 'horizon',
      silhouette: 'archer',
      widthFrac: 0.05,
      heightFrac: 0.12,
      anchor: { xFrac: 0, yFrac: 0 },
      opacity: 0.28,
      design: {
        attribute: 'quiver-rack',
        form: 'detached-mass',
        stance: 'kneeling',
        note: 'Dominant: a standing rack of shafts a pace away. Stance: one knee down on the step, drawing across.',
      },
    },
    {
      id: 'aw-torii-warden',
      tier: 'horizon',
      silhouette: 'stonewalker',
      widthFrac: 0.06,
      heightFrac: 0.17,
      anchor: { xFrac: 0.34, yFrac: 0 },
      opacity: 0.34,
      design: {
        attribute: 'torii-yoke',
        form: 'detached-mass',
        stance: 'planted',
        note: 'Dominant: a gate yoke standing apart, framing it without touching. Stance: planted dead centre of the road.',
      },
    },
    {
      id: 'aw-kite-scout',
      tier: 'horizon',
      // Not `rider` - the scout is not mounted, it is slung under a frame, and `rider` is
      // registered CLOSE_TIERS only. `harpooner` is the one horizon-legal body whose spar
      // reads as something carried clear of the torso at forty pixels.
      silhouette: 'harpooner',
      widthFrac: 0.05,
      heightFrac: 0.1,
      anchor: { xFrac: 0.68, yFrac: 0.3 },
      opacity: 0.36,
      design: {
        attribute: 'kite-frame',
        form: 'detached-mass',
        stance: 'aloft',
        note: 'Dominant: a box frame riding well above the body. Stance: airborne and slewed, knees drawn up.',
      },
    },
    {
      id: 'aw-mask-runner',
      tier: 'mid',
      silhouette: 'lancer',
      widthFrac: 0.13,
      heightFrac: 0.26,
      anchor: { xFrac: -0.62, yFrac: 0 },
      opacity: 0.56,
      design: {
        attribute: 'mask-plate',
        form: 'detached-mass',
        stance: 'lunging',
        note: 'Dominant: a mask carried out on the pole arm, clear of the head. Stance: lunging low along the road.',
      },
    },
    {
      id: 'aw-paper-standard',
      tier: 'mid',
      silhouette: 'standard-bearer',
      widthFrac: 0.1,
      heightFrac: 0.3,
      anchor: { xFrac: -0.18, yFrac: 0 },
      opacity: 0.56,
      design: {
        attribute: 'banner-cross',
        form: 'evenodd-hole',
        stance: 'leaning',
        note: 'Dominant: a paper standard that is mostly the cross of holes ash has eaten. Stance: leaning off the pole.',
      },
    },
    {
      id: 'aw-ash-serpent',
      tier: 'mid',
      silhouette: 'serpent',
      widthFrac: 0.16,
      heightFrac: 0.22,
      anchor: { xFrac: 0.24, yFrac: 0 },
      opacity: 0.54,
      design: {
        attribute: 'split-jaw',
        form: 'evenodd-hole',
        stance: 'coiled',
        note: 'Dominant: a jaw hinged open on a punched gap. Stance: coiled in the roadside ditch, head on the coil.',
      },
    },
    {
      id: 'aw-brazier-tender',
      tier: 'mid',
      silhouette: 'shieldbearer',
      widthFrac: 0.11,
      heightFrac: 0.24,
      anchor: { xFrac: 0.66, yFrac: 0 },
      opacity: 0.58,
      design: {
        attribute: 'brazier-bowl',
        form: 'detached-mass',
        stance: 'crouched',
        note: 'Dominant: a standing fire bowl it crouches beside, never over. Stance: crouched on both heels, shield down.',
      },
    },
    {
      id: 'aw-lantern-warden',
      tier: 'fore',
      silhouette: 'stonewalker',
      widthFrac: 0.24,
      heightFrac: 0.56,
      anchor: { xFrac: -0.64, yFrac: 0 },
      opacity: 0.82,
      design: {
        attribute: 'lantern-cage',
        form: 'detached-mass',
        stance: 'planted',
        note: 'Dominant: a stone lantern standing free at its side. Stance: planted, weight even, arms at its sides.',
      },
    },
    {
      id: 'aw-helm-colossus',
      tier: 'fore',
      silhouette: 'colossus',
      widthFrac: 0.3,
      heightFrac: 0.72,
      anchor: { xFrac: 0.02, yFrac: 0 },
      opacity: 0.88,
      design: {
        attribute: 'hollow-crown',
        form: 'evenodd-hole',
        stance: 'hunched',
        note: 'Dominant: a horned helm with both eye slots punched clean through. Stance: hunched forward, head dropped.',
      },
    },
    {
      id: 'aw-ring-rider',
      tier: 'fore',
      silhouette: 'rider',
      widthFrac: 0.22,
      heightFrac: 0.5,
      anchor: { xFrac: 0.7, yFrac: 0 },
      opacity: 0.8,
      design: {
        attribute: 'ring-blade',
        form: 'detached-mass',
        stance: 'pivoting',
        note: 'Dominant: a ring blade orbiting a full body-width out. Stance: pivoting the mount hard across the road.',
      },
    },
  ],
  timeline: defineTimeline('ashfall-war', 36000, [
    lit({
      id: 'aw-b1',
      title: 'ash begins',
      atMs: 0,
      durationMs: 3000,
      pressureDelayMs: 700,
      shape: 'swell',
      attackMs: 1200,
      holdMs: 800,
      releaseMs: 1000,
      peak: { emisIntensity: 1.2, shaftOpacity: 0.16 },
    }),
    rest({ id: 'aw-b2', title: 'the approach empties', atMs: 3600, durationMs: 3200 }),
    lit({
      id: 'aw-b3',
      title: 'one bell',
      atMs: 7200,
      durationMs: 1400,
      pressureDelayMs: 720,
      shape: 'strike',
      attackMs: 60,
      holdMs: 240,
      releaseMs: 1100,
      peak: { emisIntensity: 2.4, rimBoost: 1.4, brazierGlow: 1 },
    }),
    lit({
      id: 'aw-b4',
      title: 'braziers lit along the way',
      atMs: 9200,
      durationMs: 2400,
      pressureDelayMs: 710,
      shape: 'swell',
      attackMs: 1000,
      holdMs: 600,
      releaseMs: 800,
      peak: { brazierGlow: 2.2, emisIntensity: 1.8 },
    }),
    lit({
      id: 'aw-b5',
      title: 'the rank passes',
      atMs: 12200,
      durationMs: 2600,
      pressureDelayMs: 730,
      shape: 'pulse',
      attackMs: 700,
      holdMs: 700,
      releaseMs: 1200,
      peak: { emisIntensity: 1.9, shaftOpacity: 0.32 },
    }),
    rest({ id: 'aw-b6', title: 'held', atMs: 15400, durationMs: 3400 }),
    lit({
      id: 'aw-b7',
      title: 'first cut',
      atMs: 19400,
      durationMs: 1000,
      pressureDelayMs: 780,
      shape: 'strike',
      attackMs: 25,
      holdMs: 175,
      releaseMs: 800,
      peak: { emisIntensity: 3.6, rimBoost: 2.6, skyDim: 0.36 },
    }),
    lit({
      id: 'aw-b8',
      title: 'second cut',
      atMs: 20800,
      durationMs: 1000,
      pressureDelayMs: 800,
      shape: 'strike',
      attackMs: 25,
      holdMs: 175,
      releaseMs: 800,
      peak: { emisIntensity: 4.4, rimBoost: 3.2, skyDim: 0.48 },
    }),
    lit({
      id: 'aw-b9',
      title: 'ashfall smothers the lanterns',
      atMs: 22400,
      durationMs: 2800,
      pressureDelayMs: 770,
      shape: 'smother',
      attackMs: 900,
      holdMs: 1100,
      releaseMs: 800,
      peak: { skyDim: 0.86, emisIntensity: 0.32, brazierGlow: 0.3 },
    }),
    lit({
      id: 'aw-b10',
      title: 'the road, after',
      atMs: 25800,
      durationMs: 4200,
      pressureDelayMs: 740,
      shape: 'swell',
      attackMs: 1600,
      holdMs: 1400,
      releaseMs: 1200,
      peak: { emisIntensity: 1.25, brazierGlow: 0.9, shaftOpacity: 0.12 },
    }),
  ]),
});
