/**
 * FOLDWORKS HOST - machines that fight by unfolding.
 *
 * The only roster with a METRONOME. Three of its beats are the same press cycle at rising
 * intensity, evenly spaced, which makes the two hammer drops and the jam land as breaks in a
 * rhythm rather than as isolated flashes. The loop is also the shortest of the seven: the
 * works repeat, that is what works do.
 *
 * Cast logic: a machine-titan reads as a machine only if you can see the JOINT. Every figure
 * here is articulated somewhere obvious - a hinge stack, a boom, a spool, a cantilever - and
 * the fore trio is deliberately caught mid-cycle, half open, so the silhouette is a shape
 * that could not hold itself still.
 *
 * IP: original. Dockyard, loom and forging-press geometry. Nothing here disguises itself as
 * anything else, wears a badge or carries a colour identity - these are works, not warriors.
 */

import { defineTimeline } from '../types';
import { defineRoster, lit, rest, type DesignedRoster } from './design';

export const FOLDWORKS_HOST: DesignedRoster = defineRoster({
  id: 'foldworks-host',
  displayName: 'The Foldworks Host',
  figures: [
    {
      id: 'fh-spool-gantry',
      tier: 'horizon',
      silhouette: 'siege-frame',
      widthFrac: 0.07,
      heightFrac: 0.17,
      anchor: { xFrac: -0.72, yFrac: 0.06 },
      opacity: 0.3,
      design: {
        attribute: 'spool-drum',
        form: 'detached-mass',
        stance: 'suspended',
        note: 'Dominant: a fat drum hanging in the open middle of the frame. Stance: the whole gantry hung, swaying.',
      },
    },
    {
      id: 'fh-swarf-flock',
      tier: 'horizon',
      silhouette: 'flock',
      widthFrac: 0.09,
      heightFrac: 0.06,
      anchor: { xFrac: -0.38, yFrac: 0.3 },
      opacity: 0.28,
      design: {
        attribute: 'saw-comb',
        form: 'evenodd-hole',
        stance: 'aloft',
        note: 'Dominant: each body slotted through with a comb of gaps. Stance: airborne, holding a ragged line abreast.',
      },
    },
    {
      id: 'fh-press-walker',
      tier: 'horizon',
      silhouette: 'stonewalker',
      widthFrac: 0.06,
      heightFrac: 0.16,
      anchor: { xFrac: -0.02, yFrac: 0 },
      opacity: 0.32,
      design: {
        attribute: 'counterweight-boom',
        form: 'detached-mass',
        stance: 'striding',
        note: 'Dominant: a weighted boom hung out to one side, clear of the hull. Stance: striding, rolling on each step.',
      },
    },
    {
      id: 'fh-fold-lancer',
      tier: 'horizon',
      silhouette: 'lancer',
      widthFrac: 0.05,
      heightFrac: 0.14,
      anchor: { xFrac: 0.32, yFrac: 0.04 },
      opacity: 0.34,
      design: {
        attribute: 'ring-blade',
        form: 'detached-mass',
        stance: 'pivoting',
        note: 'Dominant: a ring orbiting a clear body-width away. Stance: pivoting on one heel to keep the ring out.',
      },
    },
    {
      id: 'fh-rack-standard',
      tier: 'horizon',
      silhouette: 'standard-bearer',
      widthFrac: 0.04,
      heightFrac: 0.15,
      anchor: { xFrac: 0.66, yFrac: 0 },
      opacity: 0.36,
      design: {
        attribute: 'ladder-back',
        form: 'evenodd-hole',
        stance: 'planted',
        note: 'Dominant: a rack of rungs punched through from shoulder to heel. Stance: planted, both feet parallel.',
      },
    },
    {
      id: 'fh-hinge-titan',
      tier: 'mid',
      silhouette: 'colossus',
      widthFrac: 0.17,
      heightFrac: 0.4,
      anchor: { xFrac: -0.62, yFrac: 0 },
      opacity: 0.58,
      design: {
        attribute: 'hinge-stack',
        form: 'evenodd-hole',
        stance: 'leaning',
        note: 'Dominant: a stack of plates read by the daylight between them. Stance: leaning, half its plates racked open.',
      },
    },
    {
      id: 'fh-loom-serpent',
      tier: 'mid',
      silhouette: 'serpent',
      widthFrac: 0.15,
      heightFrac: 0.22,
      anchor: { xFrac: -0.18, yFrac: 0 },
      opacity: 0.54,
      design: {
        attribute: 'claw-hook',
        form: 'detached-mass',
        stance: 'coiled',
        note: 'Dominant: a shuttle hook riding free above the coil. Stance: coiled flat in three turns, head inward.',
      },
    },
    {
      id: 'fh-crane-rider',
      tier: 'mid',
      silhouette: 'rider',
      widthFrac: 0.12,
      heightFrac: 0.28,
      anchor: { xFrac: 0.24, yFrac: 0.06 },
      opacity: 0.56,
      design: {
        attribute: 'cantilever-arm',
        form: 'detached-mass',
        stance: 'tethered',
        note: 'Dominant: an arm reaching out past everything else in the tier. Stance: held off the deck on a taut line.',
      },
    },
    {
      id: 'fh-punch-frame',
      tier: 'mid',
      silhouette: 'siege-frame',
      widthFrac: 0.18,
      heightFrac: 0.32,
      anchor: { xFrac: 0.66, yFrac: 0 },
      opacity: 0.6,
      design: {
        attribute: 'drill-cone',
        form: 'detached-mass',
        stance: 'braced',
        note: 'Dominant: a cone standing on its point in front of the frame. Stance: legs jacked out wide and braced.',
      },
    },
    {
      id: 'fh-unfolding-titan',
      tier: 'fore',
      silhouette: 'colossus',
      widthFrac: 0.3,
      heightFrac: 0.74,
      anchor: { xFrac: -0.64, yFrac: 0 },
      opacity: 0.88,
      design: {
        attribute: 'scaffold-yoke',
        form: 'detached-mass',
        stance: 'braced',
        note: 'Dominant: the yoke it is unfolding out of, standing free behind it. Stance: braced wide, mid-extension.',
      },
    },
    {
      id: 'fh-drop-press',
      tier: 'fore',
      silhouette: 'siege-frame',
      widthFrac: 0.26,
      heightFrac: 0.6,
      anchor: { xFrac: 0.04, yFrac: 0.1 },
      opacity: 0.84,
      design: {
        attribute: 'ballast-stone',
        form: 'detached-mass',
        stance: 'suspended',
        note: 'Dominant: a hammer block hanging high in clear air inside the frame. Stance: the frame itself hung and level.',
      },
    },
    {
      id: 'fh-fold-wyrm',
      tier: 'fore',
      silhouette: 'wyrm',
      widthFrac: 0.24,
      heightFrac: 0.5,
      anchor: { xFrac: 0.7, yFrac: 0 },
      opacity: 0.8,
      design: {
        attribute: 'crest-fin',
        form: 'evenodd-hole',
        stance: 'coiled',
        note: 'Dominant: a folding fin read by the slots between its leaves. Stance: coiled around its own tail, head low.',
      },
    },
  ],
  timeline: defineTimeline('foldworks-host', 22000, [
    lit({
      id: 'fh-b1',
      title: 'press cycle, one',
      atMs: 0,
      durationMs: 1200,
      pressureDelayMs: 700,
      shape: 'pulse',
      attackMs: 300,
      holdMs: 300,
      releaseMs: 600,
      peak: { emisIntensity: 1.6, brazierGlow: 1 },
    }),
    lit({
      id: 'fh-b2',
      title: 'press cycle, two',
      atMs: 1800,
      durationMs: 1200,
      pressureDelayMs: 700,
      shape: 'pulse',
      attackMs: 300,
      holdMs: 300,
      releaseMs: 600,
      peak: { emisIntensity: 1.8, brazierGlow: 1.2 },
    }),
    lit({
      id: 'fh-b3',
      title: 'the titan unfolds',
      atMs: 3600,
      durationMs: 2000,
      pressureDelayMs: 720,
      shape: 'swell',
      attackMs: 800,
      holdMs: 500,
      releaseMs: 700,
      peak: { emisIntensity: 2.2, shaftOpacity: 0.42 },
    }),
    lit({
      id: 'fh-b4',
      title: 'hammer drop',
      atMs: 6200,
      durationMs: 900,
      pressureDelayMs: 780,
      shape: 'strike',
      attackMs: 25,
      holdMs: 175,
      releaseMs: 700,
      peak: { emisIntensity: 3.4, rimBoost: 2.2, brazierGlow: 2.4 },
    }),
    rest({ id: 'fh-b5', title: 'swarf settles', atMs: 7600, durationMs: 2800 }),
    lit({
      id: 'fh-b6',
      title: 'press cycle, three',
      atMs: 10800,
      durationMs: 1200,
      pressureDelayMs: 710,
      shape: 'pulse',
      attackMs: 300,
      holdMs: 300,
      releaseMs: 600,
      peak: { emisIntensity: 2, brazierGlow: 1.4, rimBoost: 0.6 },
    }),
    lit({
      id: 'fh-b7',
      title: 'hammer drop, heavier',
      atMs: 12600,
      durationMs: 1000,
      pressureDelayMs: 800,
      shape: 'strike',
      attackMs: 25,
      holdMs: 175,
      releaseMs: 800,
      peak: { emisIntensity: 4.2, rimBoost: 2.8, brazierGlow: 3 },
    }),
    lit({
      id: 'fh-b8',
      title: 'the line jams',
      atMs: 14200,
      durationMs: 1600,
      pressureDelayMs: 760,
      shape: 'smother',
      attackMs: 500,
      holdMs: 500,
      releaseMs: 600,
      peak: { skyDim: 0.68, emisIntensity: 0.5, brazierGlow: 0.2 },
    }),
    lit({
      id: 'fh-b9',
      title: 'restart surge',
      atMs: 16400,
      durationMs: 1400,
      pressureDelayMs: 740,
      shape: 'strike',
      attackMs: 40,
      holdMs: 360,
      releaseMs: 1000,
      peak: { emisIntensity: 3.8, shaftOpacity: 0.5, rimBoost: 1.8 },
    }),
    lit({
      id: 'fh-b10',
      title: 'the works run on',
      atMs: 18200,
      durationMs: 3200,
      pressureDelayMs: 730,
      shape: 'swell',
      attackMs: 1200,
      holdMs: 1000,
      releaseMs: 1000,
      peak: { emisIntensity: 1.9, brazierGlow: 1.6, shaftOpacity: 0.24 },
    }),
  ]),
});
