/**
 * INCURSION HOST - the thing on the other side of the tear, already halfway through.
 *
 * The fastest, loudest loop of the seven: eight of its ten beats fire, three of them are
 * strikes, and the single rest sits early so the second half never gets to breathe. The loop
 * ends OPEN - the last beat is a long swell that does not fall back to neutral, because the
 * breach does not close.
 *
 * Cast logic: everything is machinery for getting through a hole and pulling something back.
 * Borers, gantries, hooks, tethers. Nothing in this roster is symmetrical and nothing is
 * standing still - the stance set is the most agitated of the seven, so the attributes are
 * mostly detached masses that trail, hang or swing behind their owners.
 *
 * IP: original. Siege machinery and insect-frame geometry. No faction, no mark, no crest.
 */

import { defineTimeline } from '../types';
import { defineRoster, lit, rest, type DesignedRoster } from './design';

export const INCURSION_HOST: DesignedRoster = defineRoster({
  id: 'incursion-host',
  displayName: 'The Breach Host',
  figures: [
    {
      id: 'ih-breach-borer',
      tier: 'horizon',
      silhouette: 'siege-frame',
      widthFrac: 0.07,
      heightFrac: 0.18,
      anchor: { xFrac: -0.72, yFrac: 0.1 },
      opacity: 0.3,
      design: {
        attribute: 'drill-cone',
        form: 'detached-mass',
        stance: 'suspended',
        note: 'Dominant: a cone hanging below the frame with clear air around it. Stance: hung off a gantry, turning.',
      },
    },
    {
      id: 'ih-tether-rider',
      tier: 'horizon',
      // Not `rider`: nothing is being ridden here and that shape is CLOSE_TIERS only.
      // `harpooner` gives the swept-back arms and the trailing line a falling figure needs.
      silhouette: 'harpooner',
      widthFrac: 0.05,
      heightFrac: 0.12,
      anchor: { xFrac: -0.4, yFrac: 0.28 },
      opacity: 0.28,
      design: {
        attribute: 'ballast-stone',
        form: 'detached-mass',
        stance: 'falling',
        note: 'Dominant: a stone dropping away below it. Stance: falling head-down, arms swept back.',
      },
    },
    {
      id: 'ih-harvest-flock',
      tier: 'horizon',
      silhouette: 'flock',
      widthFrac: 0.08,
      heightFrac: 0.07,
      anchor: { xFrac: -0.02, yFrac: 0.34 },
      opacity: 0.32,
      design: {
        attribute: 'claw-hook',
        form: 'detached-mass',
        stance: 'aloft',
        note: 'Dominant: hooks trailing well below each body. Stance: airborne in a loose descending wedge.',
      },
    },
    {
      id: 'ih-spar-lancer',
      tier: 'horizon',
      silhouette: 'lancer',
      widthFrac: 0.05,
      heightFrac: 0.13,
      anchor: { xFrac: 0.34, yFrac: 0 },
      opacity: 0.34,
      design: {
        attribute: 'pike-bundle',
        form: 'detached-mass',
        stance: 'braced',
        note: 'Dominant: a bundle of spars planted in the ground beside it. Stance: braced low behind them.',
      },
    },
    {
      id: 'ih-mound-walker',
      tier: 'horizon',
      silhouette: 'stonewalker',
      widthFrac: 0.06,
      heightFrac: 0.15,
      anchor: { xFrac: 0.66, yFrac: 0 },
      opacity: 0.36,
      design: {
        attribute: 'ladder-back',
        form: 'evenodd-hole',
        stance: 'striding',
        note: 'Dominant: rungs of daylight punched down its back. Stance: a long unhurried stride, arms slack.',
      },
    },
    {
      id: 'ih-gantry-strider',
      tier: 'mid',
      silhouette: 'siege-frame',
      widthFrac: 0.16,
      heightFrac: 0.34,
      anchor: { xFrac: -0.62, yFrac: 0 },
      opacity: 0.58,
      design: {
        attribute: 'cantilever-arm',
        form: 'detached-mass',
        stance: 'leaning',
        note: 'Dominant: an arm cantilevered far out past the frame. Stance: the whole frame tipped after it.',
      },
    },
    {
      id: 'ih-hook-serpent',
      tier: 'mid',
      silhouette: 'serpent',
      widthFrac: 0.15,
      heightFrac: 0.22,
      anchor: { xFrac: -0.2, yFrac: 0 },
      opacity: 0.54,
      design: {
        attribute: 'split-jaw',
        form: 'evenodd-hole',
        stance: 'coiled',
        note: 'Dominant: a hinged jaw with the gap cut through. Stance: coiled tight and low, head level.',
      },
    },
    {
      id: 'ih-breach-archer',
      tier: 'mid',
      silhouette: 'archer',
      widthFrac: 0.1,
      heightFrac: 0.24,
      anchor: { xFrac: 0.24, yFrac: 0 },
      opacity: 0.56,
      design: {
        attribute: 'quiver-rack',
        form: 'detached-mass',
        stance: 'kneeling',
        note: 'Dominant: a rack of shafts dug in a pace to its left. Stance: both knees down, torso square.',
      },
    },
    {
      id: 'ih-breach-standard',
      tier: 'mid',
      silhouette: 'standard-bearer',
      widthFrac: 0.11,
      heightFrac: 0.3,
      anchor: { xFrac: 0.66, yFrac: 0 },
      opacity: 0.6,
      design: {
        attribute: 'banner-cross',
        form: 'evenodd-hole',
        stance: 'planted',
        note: 'Dominant: a banner read entirely by the cross of holes torn through it. Stance: planted, both hands high.',
      },
    },
    {
      id: 'ih-wall-breaker',
      tier: 'fore',
      silhouette: 'colossus',
      widthFrac: 0.26,
      heightFrac: 0.58,
      anchor: { xFrac: -0.62, yFrac: 0 },
      opacity: 0.84,
      design: {
        attribute: 'wheel-rim',
        form: 'detached-mass',
        stance: 'hunched',
        note: 'Dominant: a broken rim standing on edge beside it. Stance: hunched forward over its own knuckles.',
      },
    },
    {
      id: 'ih-borer-wyrm',
      tier: 'fore',
      silhouette: 'wyrm',
      widthFrac: 0.22,
      heightFrac: 0.66,
      anchor: { xFrac: 0.04, yFrac: 0 },
      opacity: 0.88,
      design: {
        attribute: 'saw-comb',
        form: 'evenodd-hole',
        stance: 'reared',
        note: 'Dominant: a comb of slots cut through its flank. Stance: reared vertical, tail still in the ground.',
      },
    },
    {
      id: 'ih-gaff-harpooner',
      tier: 'fore',
      silhouette: 'harpooner',
      widthFrac: 0.24,
      heightFrac: 0.5,
      anchor: { xFrac: 0.68, yFrac: 0 },
      opacity: 0.82,
      design: {
        attribute: 'harpoon-rig',
        form: 'detached-mass',
        stance: 'lunging',
        note: 'Dominant: a rig already loosed and flying clear ahead. Stance: lunging after it, back leg trailing.',
      },
    },
  ],
  timeline: defineTimeline('incursion-host', 24000, [
    lit({
      id: 'ih-b1',
      title: 'the far column ignites',
      atMs: 0,
      durationMs: 1600,
      pressureDelayMs: 700,
      shape: 'swell',
      attackMs: 600,
      holdMs: 400,
      releaseMs: 600,
      peak: { emisIntensity: 1.6, brazierGlow: 1.1 },
    }),
    lit({
      id: 'ih-b2',
      title: 'the borer bites',
      atMs: 1900,
      durationMs: 900,
      pressureDelayMs: 740,
      shape: 'strike',
      attackMs: 40,
      holdMs: 140,
      releaseMs: 720,
      peak: { emisIntensity: 2.8, rimBoost: 1.6, skyDim: 0.3 },
    }),
    lit({
      id: 'ih-b3',
      title: 'it bites again',
      atMs: 3100,
      durationMs: 900,
      pressureDelayMs: 760,
      shape: 'strike',
      attackMs: 40,
      holdMs: 140,
      releaseMs: 720,
      peak: { emisIntensity: 3.1, rimBoost: 1.8, skyDim: 0.34 },
    }),
    lit({
      id: 'ih-b4',
      title: 'the frames advance',
      atMs: 4400,
      durationMs: 1800,
      pressureDelayMs: 720,
      shape: 'pulse',
      attackMs: 500,
      holdMs: 500,
      releaseMs: 800,
      peak: { shaftOpacity: 0.38, emisIntensity: 2 },
    }),
    rest({ id: 'ih-b5', title: 'held breath', atMs: 6600, durationMs: 2900 }),
    lit({
      id: 'ih-b6',
      title: 'the breach flares wide',
      atMs: 9800,
      durationMs: 1000,
      pressureDelayMs: 790,
      shape: 'strike',
      attackMs: 30,
      holdMs: 170,
      releaseMs: 800,
      peak: { emisIntensity: 5.2, rimBoost: 3, skyDim: 0.58, shaftOpacity: 0.6 },
    }),
    lit({
      id: 'ih-b7',
      title: 'the swarm crosses',
      atMs: 11200,
      durationMs: 2000,
      pressureDelayMs: 710,
      shape: 'pulse',
      attackMs: 450,
      holdMs: 650,
      releaseMs: 900,
      peak: { shaftOpacity: 0.52, emisIntensity: 2.4, brazierGlow: 1.6 },
    }),
    lit({
      id: 'ih-b8',
      title: 'the ram lands',
      atMs: 13600,
      durationMs: 1200,
      pressureDelayMs: 800,
      shape: 'strike',
      attackMs: 30,
      holdMs: 220,
      releaseMs: 950,
      peak: { emisIntensity: 4, rimBoost: 2.7, brazierGlow: 2.2 },
    }),
    lit({
      id: 'ih-b9',
      title: 'the dark rushes back in',
      atMs: 15200,
      durationMs: 2200,
      pressureDelayMs: 770,
      shape: 'smother',
      attackMs: 600,
      holdMs: 800,
      releaseMs: 800,
      peak: { skyDim: 0.88, emisIntensity: 0.35 },
    }),
    lit({
      id: 'ih-b10',
      title: 'the breach holds open',
      atMs: 17800,
      durationMs: 3600,
      pressureDelayMs: 730,
      shape: 'swell',
      attackMs: 1400,
      holdMs: 1100,
      releaseMs: 1100,
      peak: { emisIntensity: 2.2, shaftOpacity: 0.7, brazierGlow: 1.4, rimBoost: 1 },
    }),
  ]),
});
