/**
 * SALTGLASS FLEETS - two crews taking each other's hulls apart in a standing swell.
 *
 * The loop is tidal rather than percussive: long swells, one deep trough, and the single
 * strike held back until the seventh beat so the breach reads as an event rather than as
 * rhythm. It is the longest breathing loop in the game after the ashfall approach.
 *
 * Cast logic: a boarding action is a fight about REACH, so the roster is built from things
 * that extend - gaffs, spars, chains, harpoons, a cantilevered ramp - every one of them a
 * detached mass thrown clear of its owner. The two hulks in the fore tier are the only
 * closed shapes, which is what makes the reaching read.
 *
 * IP: original. Working rigging and hauling gear. No flag, no mark, no crew colours and no
 * costume - these are silhouettes of labour, not a named crew from anywhere.
 */

import { defineTimeline } from '../types';
import { defineRoster, lit, rest, type DesignedRoster } from './design';

export const SALTGLASS_FLEETS: DesignedRoster = defineRoster({
  id: 'saltglass-fleets',
  displayName: 'The Saltglass Fleets',
  figures: [
    {
      id: 'sf-mast-rank',
      tier: 'horizon',
      silhouette: 'flock',
      widthFrac: 0.08,
      heightFrac: 0.1,
      anchor: { xFrac: -0.7, yFrac: 0.04 },
      opacity: 0.3,
      design: {
        attribute: 'mast-spar',
        form: 'detached-mass',
        stance: 'climbing',
        note: 'Dominant: bare spars standing above and clear of the bodies. Stance: a crew climbing them in file.',
      },
    },
    {
      id: 'sf-sounding-diver',
      tier: 'horizon',
      silhouette: 'harpooner',
      widthFrac: 0.04,
      heightFrac: 0.12,
      anchor: { xFrac: -0.36, yFrac: 0.2 },
      opacity: 0.28,
      design: {
        attribute: 'ballast-stone',
        form: 'detached-mass',
        stance: 'falling',
        note: 'Dominant: a sounding weight already well below it. Stance: falling feet-first, body straight.',
      },
    },
    {
      id: 'sf-shoal-serpent',
      tier: 'horizon',
      silhouette: 'serpent',
      widthFrac: 0.09,
      heightFrac: 0.07,
      anchor: { xFrac: 0, yFrac: 0 },
      opacity: 0.32,
      design: {
        attribute: 'tail-fluke',
        form: 'detached-mass',
        stance: 'wading',
        note: 'Dominant: a fluke broken clear of the surface far behind the head. Stance: half-submerged, pushing shoreward.',
      },
    },
    {
      id: 'sf-kite-signaller',
      tier: 'horizon',
      silhouette: 'archer',
      widthFrac: 0.05,
      heightFrac: 0.14,
      anchor: { xFrac: 0.34, yFrac: 0.18 },
      opacity: 0.34,
      design: {
        attribute: 'kite-frame',
        form: 'detached-mass',
        stance: 'aloft',
        note: 'Dominant: a rigid signal frame flying well above it. Stance: hauled off the deck, legs hanging.',
      },
    },
    {
      id: 'sf-salt-walker',
      tier: 'horizon',
      silhouette: 'stonewalker',
      widthFrac: 0.06,
      heightFrac: 0.13,
      anchor: { xFrac: 0.68, yFrac: 0 },
      opacity: 0.36,
      design: {
        attribute: 'crest-fin',
        form: 'evenodd-hole',
        stance: 'wading',
        note: 'Dominant: a salt crest read by the holes eaten through it. Stance: waist deep, leaning on the current.',
      },
    },
    {
      id: 'sf-gaff-crew',
      tier: 'mid',
      silhouette: 'harpooner',
      widthFrac: 0.13,
      heightFrac: 0.26,
      anchor: { xFrac: -0.62, yFrac: 0 },
      opacity: 0.56,
      design: {
        attribute: 'boarding-gaff',
        form: 'detached-mass',
        stance: 'lunging',
        note: 'Dominant: a gaff hook thrown out ahead, touching nothing. Stance: lunging across the gap after it.',
      },
    },
    {
      id: 'sf-net-hauler',
      tier: 'mid',
      silhouette: 'stonewalker',
      widthFrac: 0.12,
      heightFrac: 0.24,
      anchor: { xFrac: -0.2, yFrac: 0 },
      opacity: 0.54,
      design: {
        attribute: 'net-drum',
        form: 'evenodd-hole',
        stance: 'hunched',
        note: 'Dominant: a drum read by the mesh punched through it. Stance: hunched right over, hauling from the hip.',
      },
    },
    {
      id: 'sf-rigging-rider',
      tier: 'mid',
      silhouette: 'rider',
      widthFrac: 0.11,
      heightFrac: 0.3,
      anchor: { xFrac: 0.22, yFrac: 0.1 },
      opacity: 0.58,
      design: {
        attribute: 'anchor-chain',
        form: 'detached-mass',
        stance: 'suspended',
        note: 'Dominant: heavy links swinging free below. Stance: hanging off the rigging by one arm, feet loose.',
      },
    },
    {
      id: 'sf-boarding-ramp',
      tier: 'mid',
      silhouette: 'siege-frame',
      widthFrac: 0.18,
      heightFrac: 0.28,
      anchor: { xFrac: 0.66, yFrac: 0 },
      opacity: 0.6,
      design: {
        attribute: 'cantilever-arm',
        form: 'detached-mass',
        stance: 'leaning',
        note: 'Dominant: a ramp run far out past the hull line. Stance: the frame tipped forward under its own reach.',
      },
    },
    {
      id: 'sf-boarding-colossus',
      tier: 'fore',
      silhouette: 'colossus',
      widthFrac: 0.28,
      heightFrac: 0.64,
      anchor: { xFrac: -0.58, yFrac: 0 },
      opacity: 0.84,
      design: {
        attribute: 'claw-hook',
        form: 'detached-mass',
        stance: 'climbing',
        note: 'Dominant: a grapnel hanging free beneath its reach. Stance: climbing a hull, one leg cocked high.',
      },
    },
    {
      id: 'sf-breaching-wyrm',
      tier: 'fore',
      silhouette: 'wyrm',
      widthFrac: 0.3,
      heightFrac: 0.58,
      anchor: { xFrac: 0.54, yFrac: 0 },
      opacity: 0.88,
      design: {
        attribute: 'split-jaw',
        form: 'evenodd-hole',
        stance: 'reared',
        note: 'Dominant: a jaw open on a punched void the size of its own skull. Stance: reared out of the swell.',
      },
    },
  ],
  timeline: defineTimeline('saltglass-fleets', 32000, [
    lit({
      id: 'sf-b1',
      title: 'the swell lifts the fleet',
      atMs: 0,
      durationMs: 2600,
      pressureDelayMs: 710,
      shape: 'swell',
      attackMs: 1000,
      holdMs: 700,
      releaseMs: 900,
      peak: { emisIntensity: 1.4, shaftOpacity: 0.3 },
    }),
    lit({
      id: 'sf-b2',
      title: 'hulls grind together',
      atMs: 3200,
      durationMs: 1800,
      pressureDelayMs: 730,
      shape: 'pulse',
      attackMs: 500,
      holdMs: 500,
      releaseMs: 800,
      peak: { emisIntensity: 1.7, rimBoost: 0.8 },
    }),
    lit({
      id: 'sf-b3',
      title: 'gaffs away',
      atMs: 5400,
      durationMs: 1200,
      pressureDelayMs: 750,
      shape: 'strike',
      attackMs: 50,
      holdMs: 250,
      releaseMs: 900,
      peak: { emisIntensity: 2.6, rimBoost: 1.7 },
    }),
    lit({
      id: 'sf-b4',
      title: 'the trough',
      atMs: 7200,
      durationMs: 2400,
      pressureDelayMs: 770,
      shape: 'smother',
      attackMs: 900,
      holdMs: 700,
      releaseMs: 800,
      peak: { skyDim: 0.5, emisIntensity: 0.7, shaftOpacity: 0.08 },
    }),
    rest({ id: 'sf-b5', title: 'becalmed', atMs: 10000, durationMs: 3200 }),
    lit({
      id: 'sf-b6',
      title: 'the sounding comes back',
      atMs: 13600,
      durationMs: 2200,
      pressureDelayMs: 700,
      shape: 'swell',
      attackMs: 900,
      holdMs: 600,
      releaseMs: 700,
      peak: { shaftOpacity: 0.55, emisIntensity: 2, brazierGlow: 1 },
    }),
    lit({
      id: 'sf-b7',
      title: 'breach',
      atMs: 16200,
      durationMs: 1200,
      pressureDelayMs: 800,
      shape: 'strike',
      attackMs: 30,
      holdMs: 170,
      releaseMs: 1000,
      peak: { emisIntensity: 4.6, rimBoost: 3, skyDim: 0.4 },
    }),
    lit({
      id: 'sf-b8',
      title: 'the hull opens',
      atMs: 17800,
      durationMs: 2000,
      pressureDelayMs: 720,
      shape: 'pulse',
      attackMs: 600,
      holdMs: 600,
      releaseMs: 800,
      peak: { emisIntensity: 2.6, brazierGlow: 1.9, rimBoost: 1.2 },
    }),
    lit({
      id: 'sf-b9',
      title: 'salt closes over it',
      atMs: 20200,
      durationMs: 2600,
      pressureDelayMs: 780,
      shape: 'smother',
      attackMs: 800,
      holdMs: 1000,
      releaseMs: 800,
      peak: { skyDim: 0.8, emisIntensity: 0.4 },
    }),
    lit({
      id: 'sf-b10',
      title: 'the fleet rides it out',
      atMs: 23200,
      durationMs: 4000,
      pressureDelayMs: 740,
      shape: 'swell',
      attackMs: 1600,
      holdMs: 1200,
      releaseMs: 1200,
      peak: { emisIntensity: 1.5, shaftOpacity: 0.34, rimBoost: 0.7 },
    }),
  ]),
});
