/**
 * VOID CHOIR - a rite, not a battle.
 *
 * The nave has no walls and no roof; the choir stands in it anyway. Nothing here charges,
 * nothing here breaks formation. The drama is entirely in the light: the corridor is smothered
 * more often than it is lit, so the two strikes land like struck bells in a silent room.
 *
 * Cast logic: this roster is deliberately the STILLEST of the seven. Its stances cluster around
 * planted, suspended and kneeling, which means the attributes carry almost the whole read - so
 * every attribute is oversized and every one of them is either standing clear of its owner or
 * punched straight through it.
 *
 * IP: original. A hollow crown, a tuning spire, a censer on a chain and a rack of unlit lanterns
 * are liturgical furniture, not anybody's character.
 */

import { defineTimeline } from '../types';
import { defineRoster, lit, rest, type DesignedRoster } from './design';

export const VOID_CHOIR: DesignedRoster = defineRoster({
  id: 'void-choir',
  displayName: 'The Hollow Choir',
  figures: [
    {
      id: 'vc-cantor-hollow',
      tier: 'horizon',
      silhouette: 'colossus',
      widthFrac: 0.07,
      heightFrac: 0.17,
      anchor: { xFrac: -0.62, yFrac: 0 },
      opacity: 0.34,
      design: {
        attribute: 'hollow-crown',
        form: 'evenodd-hole',
        stance: 'planted',
        note: 'Dominant: a ring of void where the head should be. Stance: feet wide, absolutely motionless.',
      },
    },
    {
      id: 'vc-tuning-nave',
      tier: 'horizon',
      silhouette: 'siege-frame',
      widthFrac: 0.06,
      heightFrac: 0.16,
      anchor: { xFrac: -0.3, yFrac: 0.06 },
      opacity: 0.3,
      design: {
        attribute: 'tuning-spire',
        form: 'detached-mass',
        stance: 'suspended',
        note: 'Dominant: a two-pronged spire hanging free inside the frame. Stance: hung, feet clear of the ground.',
      },
    },
    {
      id: 'vc-lantern-processional',
      tier: 'horizon',
      silhouette: 'flock',
      widthFrac: 0.08,
      heightFrac: 0.09,
      anchor: { xFrac: 0.06, yFrac: 0 },
      opacity: 0.28,
      design: {
        attribute: 'lantern-cage',
        form: 'detached-mass',
        stance: 'striding',
        note: 'Dominant: unlit cages carried out at arm length, clear of every body. Stance: a rank walking in step.',
      },
    },
    {
      id: 'vc-blind-archer',
      tier: 'horizon',
      silhouette: 'archer',
      widthFrac: 0.05,
      heightFrac: 0.1,
      anchor: { xFrac: 0.4, yFrac: 0 },
      opacity: 0.32,
      design: {
        attribute: 'quiver-rack',
        form: 'detached-mass',
        stance: 'kneeling',
        note: 'Dominant: a shaft rack standing in the ground beside it. Stance: one knee down, drawn and holding.',
      },
    },
    {
      id: 'vc-bell-mourner',
      tier: 'horizon',
      silhouette: 'standard-bearer',
      widthFrac: 0.05,
      heightFrac: 0.14,
      anchor: { xFrac: 0.68, yFrac: 0 },
      opacity: 0.36,
      design: {
        attribute: 'bell-tree',
        form: 'evenodd-hole',
        stance: 'leaning',
        note: 'Dominant: a stave of bells read by the gaps punched between them. Stance: leaning hard on the stave.',
      },
    },
    {
      id: 'vc-censer-swinger',
      tier: 'mid',
      silhouette: 'colossus',
      widthFrac: 0.12,
      heightFrac: 0.26,
      anchor: { xFrac: -0.55, yFrac: 0 },
      opacity: 0.56,
      design: {
        attribute: 'censer-chain',
        form: 'detached-mass',
        stance: 'reeling',
        note: 'Dominant: a censer at the far end of its swing, a detached lump of mass. Stance: body reeling after it.',
      },
    },
    {
      id: 'vc-keening-serpent',
      tier: 'mid',
      silhouette: 'serpent',
      widthFrac: 0.16,
      heightFrac: 0.3,
      anchor: { xFrac: -0.14, yFrac: 0.02 },
      opacity: 0.6,
      design: {
        attribute: 'split-jaw',
        form: 'evenodd-hole',
        stance: 'reared',
        note: 'Dominant: a jaw split open around a punched void. Stance: reared off the ground into a standing S.',
      },
    },
    {
      id: 'vc-rung-penitent',
      tier: 'mid',
      silhouette: 'stonewalker',
      widthFrac: 0.11,
      heightFrac: 0.24,
      anchor: { xFrac: 0.3, yFrac: 0 },
      opacity: 0.54,
      design: {
        attribute: 'ladder-back',
        form: 'evenodd-hole',
        stance: 'hunched',
        note: 'Dominant: a spine of stone rungs read by the gaps between them. Stance: hunched under its own back.',
      },
    },
    {
      id: 'vc-hollowed-lancer',
      tier: 'mid',
      silhouette: 'lancer',
      widthFrac: 0.14,
      heightFrac: 0.22,
      anchor: { xFrac: 0.68, yFrac: 0 },
      opacity: 0.58,
      design: {
        attribute: 'void-cavity',
        form: 'evenodd-hole',
        stance: 'lunging',
        note: 'Dominant: a hole clean through the torso. Stance: front foot far out, lance arm fully extended.',
      },
    },
    {
      id: 'vc-nave-colossus',
      tier: 'fore',
      silhouette: 'colossus',
      widthFrac: 0.3,
      heightFrac: 0.62,
      anchor: { xFrac: -0.48, yFrac: 0 },
      opacity: 0.86,
      design: {
        attribute: 'antler-rack',
        form: 'detached-mass',
        stance: 'seated',
        note: 'Dominant: a rack of shed spires standing behind it, touching nothing. Stance: seated, hands on knees.',
      },
    },
    {
      id: 'vc-choir-wyrm',
      tier: 'fore',
      silhouette: 'wyrm',
      widthFrac: 0.28,
      heightFrac: 0.48,
      anchor: { xFrac: 0.46, yFrac: 0 },
      opacity: 0.82,
      design: {
        attribute: 'crest-fin',
        form: 'evenodd-hole',
        stance: 'coiled',
        note: 'Dominant: a dorsal fin read by the notches cut through it. Stance: coiled flat, head laid on the coil.',
      },
    },
  ],
  timeline: defineTimeline('void-choir', 27000, [
    lit({
      id: 'vc-b1',
      title: 'the nave draws breath',
      atMs: 0,
      durationMs: 2400,
      pressureDelayMs: 760,
      shape: 'swell',
      attackMs: 900,
      holdMs: 700,
      releaseMs: 800,
      peak: { emisIntensity: 1.35, shaftOpacity: 0.18 },
    }),
    lit({
      id: 'vc-b2',
      title: 'the cantor lifts',
      atMs: 2900,
      durationMs: 1500,
      pressureDelayMs: 720,
      shape: 'pulse',
      attackMs: 260,
      holdMs: 420,
      releaseMs: 820,
      peak: { emisIntensity: 1.9, rimBoost: 0.7 },
    }),
    lit({
      id: 'vc-b3',
      title: 'first smother',
      atMs: 5000,
      durationMs: 1600,
      pressureDelayMs: 780,
      shape: 'smother',
      attackMs: 520,
      holdMs: 500,
      releaseMs: 580,
      peak: { skyDim: 0.55, emisIntensity: 0.55 },
    }),
    lit({
      id: 'vc-b4',
      title: 'the bell is struck',
      atMs: 7200,
      durationMs: 800,
      pressureDelayMs: 740,
      shape: 'strike',
      attackMs: 40,
      holdMs: 90,
      releaseMs: 670,
      peak: { emisIntensity: 3.2, rimBoost: 1.9, skyDim: 0.32 },
    }),
    rest({ id: 'vc-b5', title: 'the nave holds', atMs: 8600, durationMs: 2800 }),
    lit({
      id: 'vc-b6',
      title: 'the answering rank',
      atMs: 12000,
      durationMs: 2200,
      pressureDelayMs: 700,
      shape: 'swell',
      attackMs: 800,
      holdMs: 700,
      releaseMs: 700,
      peak: { shaftOpacity: 0.46, emisIntensity: 1.9, brazierGlow: 0.8 },
    }),
    lit({
      id: 'vc-b7',
      title: 'second bell, nearer',
      atMs: 14800,
      durationMs: 800,
      pressureDelayMs: 800,
      shape: 'strike',
      attackMs: 30,
      holdMs: 110,
      releaseMs: 660,
      peak: { emisIntensity: 4.4, rimBoost: 2.6, skyDim: 0.5 },
    }),
    lit({
      id: 'vc-b8',
      title: 'the smother deepens',
      atMs: 16200,
      durationMs: 2400,
      pressureDelayMs: 770,
      shape: 'smother',
      attackMs: 700,
      holdMs: 900,
      releaseMs: 800,
      peak: { skyDim: 0.82, emisIntensity: 0.3, shaftOpacity: 0.04 },
    }),
    lit({
      id: 'vc-b9',
      title: 'the wyrm turns over',
      atMs: 19200,
      durationMs: 1800,
      pressureDelayMs: 730,
      shape: 'pulse',
      attackMs: 420,
      holdMs: 500,
      releaseMs: 880,
      peak: { brazierGlow: 1.2, emisIntensity: 2.1, rimBoost: 0.9 },
    }),
    lit({
      id: 'vc-b10',
      title: 'hold on the empty nave',
      atMs: 21600,
      durationMs: 3400,
      pressureDelayMs: 750,
      shape: 'swell',
      attackMs: 1200,
      holdMs: 1100,
      releaseMs: 1100,
      peak: { emisIntensity: 1.15, shaftOpacity: 0.08, skyDim: 0.1 },
    }),
  ]),
});
