/**
 * ZENITH ASCENDANTS - duellists who fight by cutting away everything that holds them down.
 *
 * The only loop that ENDS AT ITS BRIGHTEST. Every other roster falls back toward neutral so
 * the corridor can breathe; this one climbs through the ten beats and holds the tenth wide
 * open for four and a half seconds, so the player finishes each pass through the loop in the
 * most exposed light in the game.
 *
 * Cast logic: altitude has to be legible without wings, glow or trailing cloth, none of which
 * survive forty pixels. So the roster carries WEIGHT instead: a cut ballast stone, an anchor
 * chain, a counterweight boom, a hanging climber. Half the cast is drawn well above the
 * horizon line and everything that has risen has visibly shed something to do it.
 *
 * IP: original. The read is entirely mass, tether and stance: no costume signature, no crest,
 * no colour identity, nothing borrowed from anything that exists.
 */

import { defineTimeline } from '../types';
import { defineRoster, lit, rest, type DesignedRoster } from './design';

export const ZENITH_ASCENDANTS: DesignedRoster = defineRoster({
  id: 'zenith-ascendants',
  displayName: 'The Zenith Ascendants',
  figures: [
    {
      id: 'za-thermal-flock',
      tier: 'horizon',
      silhouette: 'flock',
      widthFrac: 0.09,
      heightFrac: 0.06,
      anchor: { xFrac: -0.7, yFrac: 0.4 },
      opacity: 0.28,
      design: {
        attribute: 'thermal-vane',
        form: 'detached-mass',
        stance: 'aloft',
        note: 'Dominant: stiff vanes riding above and apart from each body. Stance: a flock turning on one thermal.',
      },
    },
    {
      id: 'za-ballast-cutter',
      tier: 'horizon',
      silhouette: 'lancer',
      widthFrac: 0.05,
      heightFrac: 0.13,
      anchor: { xFrac: -0.34, yFrac: 0.22 },
      opacity: 0.32,
      design: {
        attribute: 'ballast-stone',
        form: 'detached-mass',
        stance: 'falling',
        note: 'Dominant: the stone it just cut, dropping away underneath. Stance: falling backward, blade arm still out.',
      },
    },
    {
      id: 'za-anchor-warden',
      tier: 'horizon',
      silhouette: 'stonewalker',
      widthFrac: 0.06,
      heightFrac: 0.16,
      anchor: { xFrac: 0.02, yFrac: 0 },
      opacity: 0.34,
      design: {
        attribute: 'anchor-chain',
        form: 'detached-mass',
        stance: 'planted',
        note: 'Dominant: a heavy chain ring lying clear at its feet. Stance: planted, the only figure still on the ground.',
      },
    },
    {
      id: 'za-vane-archer',
      tier: 'horizon',
      silhouette: 'archer',
      widthFrac: 0.05,
      heightFrac: 0.12,
      anchor: { xFrac: 0.36, yFrac: 0.26 },
      opacity: 0.3,
      design: {
        attribute: 'ring-blade',
        form: 'detached-mass',
        stance: 'tethered',
        note: 'Dominant: a ring blade parked in the air off its shoulder. Stance: held at the end of a taut line, drawing.',
      },
    },
    {
      id: 'za-updraft-serpent',
      tier: 'horizon',
      silhouette: 'serpent',
      widthFrac: 0.08,
      heightFrac: 0.15,
      anchor: { xFrac: 0.7, yFrac: 0.12 },
      opacity: 0.36,
      design: {
        attribute: 'tail-fluke',
        form: 'detached-mass',
        stance: 'climbing',
        note: 'Dominant: a broad fluke trailing a full length behind. Stance: climbing the column nose-up in a slow screw.',
      },
    },
    {
      id: 'za-kite-duelist',
      tier: 'mid',
      silhouette: 'rider',
      widthFrac: 0.14,
      heightFrac: 0.3,
      anchor: { xFrac: -0.62, yFrac: 0.16 },
      opacity: 0.58,
      design: {
        attribute: 'kite-frame',
        form: 'evenodd-hole',
        stance: 'lunging',
        note: 'Dominant: a delta frame read by the open sky inside it. Stance: lunging out over the leading edge.',
      },
    },
    {
      id: 'za-counterweight-warden',
      tier: 'mid',
      silhouette: 'siege-frame',
      widthFrac: 0.18,
      heightFrac: 0.34,
      anchor: { xFrac: -0.16, yFrac: 0 },
      opacity: 0.56,
      design: {
        attribute: 'counterweight-boom',
        form: 'detached-mass',
        stance: 'leaning',
        note: 'Dominant: a boom and its weight swung far off to one side. Stance: the frame leaning against its own load.',
      },
    },
    {
      id: 'za-spire-climber',
      tier: 'mid',
      silhouette: 'harpooner',
      widthFrac: 0.11,
      heightFrac: 0.28,
      anchor: { xFrac: 0.26, yFrac: 0.08 },
      opacity: 0.54,
      design: {
        attribute: 'claw-hook',
        form: 'detached-mass',
        stance: 'climbing',
        note: 'Dominant: a hook already set well above its reach. Stance: climbing hand over hand, both feet off.',
      },
    },
    {
      id: 'za-mast-signal',
      tier: 'mid',
      silhouette: 'standard-bearer',
      widthFrac: 0.1,
      heightFrac: 0.32,
      anchor: { xFrac: 0.68, yFrac: 0 },
      opacity: 0.6,
      design: {
        attribute: 'mast-spar',
        form: 'detached-mass',
        stance: 'braced',
        note: 'Dominant: a bare spar stepped in the ground beside it. Stance: braced against the spar, feet split fore and aft.',
      },
    },
    {
      id: 'za-zenith-colossus',
      tier: 'fore',
      silhouette: 'colossus',
      widthFrac: 0.3,
      heightFrac: 0.76,
      anchor: { xFrac: -0.6, yFrac: 0.12 },
      opacity: 0.86,
      design: {
        attribute: 'void-cavity',
        form: 'evenodd-hole',
        stance: 'suspended',
        note: 'Dominant: a shaft of open sky punched through the torso where its ballast was. Stance: hanging, feet trailing.',
      },
    },
    {
      id: 'za-fallen-ascendant',
      tier: 'fore',
      silhouette: 'shieldbearer',
      widthFrac: 0.26,
      heightFrac: 0.58,
      anchor: { xFrac: 0.58, yFrac: 0.3 },
      opacity: 0.82,
      design: {
        attribute: 'tower-shield',
        form: 'evenodd-hole',
        stance: 'falling',
        note: 'Dominant: a shield with its whole centre punched out. Stance: falling on its back, shield still held up.',
      },
    },
  ],
  timeline: defineTimeline('zenith-ascendants', 28000, [
    lit({
      id: 'za-b1',
      title: 'the field stirs',
      atMs: 0,
      durationMs: 2000,
      pressureDelayMs: 700,
      shape: 'swell',
      attackMs: 800,
      holdMs: 500,
      releaseMs: 700,
      peak: { emisIntensity: 1.3, shaftOpacity: 0.22 },
    }),
    lit({
      id: 'za-b2',
      title: 'first ballast cut',
      atMs: 2600,
      durationMs: 1000,
      pressureDelayMs: 730,
      shape: 'strike',
      attackMs: 30,
      holdMs: 170,
      releaseMs: 800,
      peak: { emisIntensity: 2.2, rimBoost: 1.3 },
    }),
    lit({
      id: 'za-b3',
      title: 'the flock takes the thermal',
      atMs: 4200,
      durationMs: 2200,
      pressureDelayMs: 710,
      shape: 'pulse',
      attackMs: 700,
      holdMs: 600,
      releaseMs: 900,
      peak: { shaftOpacity: 0.44, emisIntensity: 1.8 },
    }),
    lit({
      id: 'za-b4',
      title: 'the colossus passes over',
      atMs: 7000,
      durationMs: 2000,
      pressureDelayMs: 760,
      shape: 'smother',
      attackMs: 600,
      holdMs: 600,
      releaseMs: 800,
      peak: { skyDim: 0.58, emisIntensity: 0.6 },
    }),
    rest({ id: 'za-b5', title: 'windless', atMs: 9600, durationMs: 3000 }),
    lit({
      id: 'za-b6',
      title: 'second ballast cut',
      atMs: 13200,
      durationMs: 1000,
      pressureDelayMs: 750,
      shape: 'strike',
      attackMs: 30,
      holdMs: 170,
      releaseMs: 800,
      peak: { emisIntensity: 3.2, rimBoost: 2.1, shaftOpacity: 0.5 },
    }),
    lit({
      id: 'za-b7',
      title: 'the duel closes',
      atMs: 14800,
      durationMs: 1800,
      pressureDelayMs: 720,
      shape: 'pulse',
      attackMs: 500,
      holdMs: 500,
      releaseMs: 800,
      peak: { emisIntensity: 2.6, rimBoost: 1.6, brazierGlow: 1.2 },
    }),
    lit({
      id: 'za-b8',
      title: 'the fall',
      atMs: 17200,
      durationMs: 1400,
      pressureDelayMs: 800,
      shape: 'strike',
      attackMs: 25,
      holdMs: 175,
      releaseMs: 1200,
      peak: { emisIntensity: 4.8, rimBoost: 3.4, skyDim: 0.44 },
    }),
    lit({
      id: 'za-b9',
      title: 'the field inhales',
      atMs: 19400,
      durationMs: 1800,
      pressureDelayMs: 780,
      shape: 'smother',
      attackMs: 600,
      holdMs: 600,
      releaseMs: 600,
      peak: { skyDim: 0.7, emisIntensity: 0.5, shaftOpacity: 0.12 },
    }),
    lit({
      id: 'za-b10',
      title: 'zenith',
      atMs: 21800,
      durationMs: 4400,
      pressureDelayMs: 740,
      shape: 'swell',
      attackMs: 2000,
      holdMs: 1400,
      releaseMs: 1000,
      peak: { emisIntensity: 3.4, shaftOpacity: 0.86, brazierGlow: 1.8, rimBoost: 1.4 },
    }),
  ]),
});
